export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_ERROR = 'GET_CONTACTS_ERROR';
export const GET_CONTACTS_CLEAR = 'GET_CONTACTS_CLEAR';

export const SET_CONTACT = 'SET_CONTACT';
export const SET_CONTACT_SUCCESS = 'SET_CONTACT_SUCCESS';
export const SET_CONTACT_ERROR = 'SET_CONTACT_ERROR';
export const SET_CONTACT_CLEAR = 'SET_CONTACT_CLEAR';

export const DEL_CONTACT = 'DEL_CONTACT';
export const DEL_CONTACT_SUCCESS = 'DEL_CONTACT_SUCCESS';
export const DEL_CONTACT_ERROR = 'DEL_CONTACT_ERROR';
export const DEL_CONTACT_CLEAR = 'DEL_CONTACT_CLEAR';

export const GET_CONTACT = 'GET_CONTACT';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';
export const GET_CONTACT_ERROR = 'GET_CONTACT_ERROR';
export const GET_CONTACT_CLEAR = 'GET_CONTACT_CLEAR';

export const PUT_CONTACT = 'PUT_CONTACT';
export const PUT_CONTACT_SUCCESS = 'PUT_CONTACT_SUCCESS';
export const PUT_CONTACT_ERROR = 'PUT_CONTACT_ERROR';
export const PUT_CONTACT_CLEAR = 'PUT_CONTACT_CLEAR';
